# Generated by Django 4.0 on 2021-12-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=255)),
                ('edept', models.CharField(choices=[('Employee', 'EM'), ('Manager', 'MG')], max_length=10)),
                ('eactive', models.BooleanField()),
            ],
        ),
    ]
